allow to kill install by sigint

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,7 +1,8 @@
 #!/bin/bash
 
-# Fail on the first error
+# Fail on the first error; killable by SIGINT
 set -e
+trap "exit" INT
 
 echo "
 ================================================
